from object_Encoder import ObjectEncoder
from clase_vehiculoNuevo import VehiculoNuevo
from clase_vehiculoUsado import VehiculoUsado
from clase_listaVehiculos import Lista
import os
def m_menu():
    print ("1: Ingresar un vehículo en una posición")
    print ("2: Agregar un vehículo a la colección")
    print ("3: Mostrar tipo de objeto de una posición de la lista")
    print ("4: Modificar precio base, y mostrar nuevo precio de venta")
    print ("5: Mostrar todos los datos del vehículo más económico")
    print ("6: Mostrar modelo, cantidad de puertas e importe de venta, de todos los vehículos")
    print ("7: Almacenar en un archivo los autos")
    print ("8: Salir")
def test(vehiculos):
    print ("Apartado 1:")
    vehiculoaux1=VehiculoNuevo("Fiat 500",4,"Gris","100000","Full","Fiat")
    vehiculoaux1.mostrar_datos()
    print ("Ingresa vehículo en la última posición de la lista\n")
    vehiculos.ingresar_vehiculo_posicion(10,vehiculoaux1)
    vehiculoaux2=VehiculoUsado("Renault Clio",4,"Negro","90000","LER042",2017,60000,"Renault")
    vehiculoaux2.mostrar_datos()
    print ("Ingresa vehículo en la primera posición de la lista\n")
    vehiculos.ingresar_vehiculo_posicion(0,vehiculoaux2)
    vehiculoaux3=VehiculoNuevo("Toyota Hylux",5,"Gris claro",120000,"Full","Toyota")
    vehiculoaux3.mostrar_datos()
    print ("Ingresa vehículo en una posición intermedia de la lista\n")
    vehiculos.ingresar_vehiculo_posicion(5,vehiculoaux3)
    print ("Lista de vehiculos para verificar:")
    vehiculos.listarVehiculos()
    print ("\nApartado 2:")
    print ("Agrega el siguiente vehículo:")
    vehiculoaux4=VehiculoUsado("Volkswagen Gol",3,"Verde oscuro",96000,"KAD420",2015,45000,"Volkswagen")
    vehiculoaux4.mostrar_datos()
    print ("\n")
    vehiculos.agregarVehiculo(vehiculoaux4)
    print ("Lista de vehiculos para verificar:")
    vehiculos.listarVehiculos()
    print ("\nApartado 3:")
    print ("Vehiculo en la primera posición:")
    vehiculos.mostrar_tipo_vehiculo(0)
    print ("\nApartado 4:")
    print ("Modificar vehiculo agregado con patente 'KAD420', y modificar precio a '85000'")
    vehiculos.modificar_precio("KAD420",85000)
if __name__ == "__main__":
    jsonV=ObjectEncoder()
    vehiculos=Lista()
    diccionario=jsonV.leerJSONArchivo('vehiculos.json')
    vehiculos=jsonV.decodificarDiccionario(diccionario)
    test(vehiculos)